spring:
  datasource:
    url: jdbc:mysql://<HOST>:3306/<DBNAME>?useSSL=true&serverTimezone=UTC
    username: <USER>
    password: <PASSWORD>
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update     # create / update tables automatically (good for dev)
    show-sql: true         # log SQL queries (disable later in prod)
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false           # so HTML changes reload in dev mode

server:
  port: 8080