spring:
  datasource:
    url: jdbc:h2:mem:accounts_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
    com.zaxxer.hikari: INFO
