CREATE TABLE IF NOT EXISTS ACCOUNT(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    address VARCHAR(255),
    phone VARCHAR(20) UNIQUE
);